# Generated by Django 3.1.5 on 2021-01-28 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], max_length=15)),
                ('dt_nasc', models.DateField(verbose_name=datetime.datetime(2021, 1, 28, 16, 23, 54, 625733))),
                ('numero', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('funcao', models.CharField(choices=[('1', 'Gerente'), ('2', 'Recepcionista'), ('3', 'cozinheiro'), ('4', 'faxineiro'), ('5', 'cliente')], max_length=10)),
                ('salario', models.FloatField(default=0)),
                ('dt_chegada', models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 28, 16, 23, 54, 625824))),
                ('dt_saida', models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 28, 16, 23, 54, 625835))),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto')),
            ],
        ),
    ]
