# Generated by Django 3.1.5 on 2021-01-29 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_chegada',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 29, 10, 14, 26, 785605)),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nasc',
            field=models.DateField(verbose_name=datetime.datetime(2021, 1, 29, 10, 14, 26, 785526)),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_saida',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 29, 10, 14, 26, 785617)),
        ),
    ]
