# Generated by Django 3.1.5 on 2021-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20210129_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_chegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nasc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_saida',
            field=models.DateTimeField(),
        ),
    ]
