# Generated by Django 3.1.5 on 2021-01-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id_quarto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('andar', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('1', 'Apartamento'), ('2', 'Suíte'), ('3', 'Normal'), ('4', 'Pernoite')], max_length=15)),
                ('descrição', models.TextField(max_length=200)),
                ('n_pessoas', models.CharField(max_length=50)),
                ('custo', models.FloatField()),
            ],
        ),
    ]
