# Generated by Django 3.1.5 on 2021-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarto',
            old_name='n_pessoas',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Suíte', 'Suíte'), ('Normal', 'Normal'), ('Pernoite', 'Pernoite')], max_length=15),
        ),
    ]
