# Generated by Django 3.1.5 on 2021-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_auto_20210210_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='id_quarto',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='quarto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='quantidade_pessoas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
